"""
agent.py — Economic Scenario Stress Test Agent (CLI orchestrator).

Usage:
    python agent.py --scenario "A sudden European banking crisis" [options]
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

import config
from historical_scenarios import ScenarioKnowledgeBase
import impact_summarizer
import ore_runner
import scenario_analyzer
import stresstest_builder
import todaysmarket_analyzer

BANNER = """
╔══════════════════════════════════════════════════════════╗
║       Economic Scenario Stress Test Agent                ║
╚══════════════════════════════════════════════════════════╝
"""

STEP = "  ▶ "
OK = "  ✓ "
WARN = "  ⚠  "


# ── Core orchestration ────────────────────────────────────────────────────────

def run(
    scenario_description: str,
    ore_workspace: Path,
    scenario_id: str = "agent_scenario",
    verbose: bool = False,
) -> str:
    """
    Full pipeline: analyze → build → run ORE → summarize.

    Parameters
    ----------
    scenario_description : free-text user scenario
    ore_workspace        : path to the OREDir workspace
    scenario_id          : identifier embedded in the stress test XML
    verbose              : print extra debug info

    Returns
    -------
    Markdown-formatted report string.
    """
    print(BANNER)
    print(f'Analyzing scenario: "{scenario_description}"\n')

    # ── Step 1: Scenario Analysis ─────────────────────────────────────────
    print(STEP + "Step 1/5  Analyzing scenario with LLM …")
    knowledge_base = ScenarioKnowledgeBase(
        config.DATA_DIR / "scenarios.json"
    )
    analysis = scenario_analyzer.analyze(scenario_description, knowledge_base)
    print(OK + "Scenario analysis complete\n")
    print(scenario_analyzer.format_shifts(analysis))
    print()

    shifts = analysis["shifts"]

    # ── Step 2: Parse market structure ────────────────────────────────────
    print(STEP + "Step 2/5  Parsing todaysmarket.xml …")
    ore_workspace = Path(ore_workspace)
    tm_xml = ore_workspace / "Input" / "todaysmarket.xml"
    market = todaysmarket_analyzer.parse(tm_xml)
    sector_map = todaysmarket_analyzer.load_sector_mapping()
    print(OK + f"Discovered {len(market.currencies)} currencies, "
          f"{len(market.discount_curves)} discount curves, "
          f"{len(market.equity_curves)} equities, "
          f"{len(market.default_curves)} credit names\n")

    # ── Step 3: Build stress test XML ─────────────────────────────────────
    print(STEP + "Step 3/5  Generating ORE stress test XML …")

    stress_xml = ore_workspace / "Input" / "agent_stress.xml"
    stresstest_builder.build(
        shifts=shifts,
        market=market,
        sector_map=sector_map,
        output_path=stress_xml,
        scenario_id=scenario_id,
        scenario_label=(
            "Generated by Economic Scenario Stress Test Agent  |  "
            "Matched: " + ", ".join(analysis["matched_scenarios"])
        ),
    )
    print(OK + f"Written: {stress_xml}")

    ore_agent_xml = ore_workspace / "ore_agent.xml"
    stresstest_builder.build_ore_config(
        base_ore_xml=ore_workspace / "ore.xml",
        output_ore_xml=ore_agent_xml,
        stress_config_file="agent_stress.xml",
        market=market,
    )
    print(OK + f"Written: {ore_agent_xml}\n")

    # ── Step 4: Run ORE ───────────────────────────────────────────────────
    print(STEP + "Step 4/5  Running ORE …")
    csv_path = ore_runner.run(
        ore_xml=ore_agent_xml,
        workspace=ore_workspace,
    )
    print(OK + f"ORE completed. Results: {csv_path}\n")

    # ── Step 5: Summarize ─────────────────────────────────────────────────
    print(STEP + "Step 5/5  Generating impact report …")
    report = impact_summarizer.summarize(
        csv_path=csv_path,
        scenario_description=scenario_description,
        shifts=shifts,
        scenario_id=scenario_id,
    )
    print(OK + "Report ready\n")

    return report


# ── CLI ───────────────────────────────────────────────────────────────────────

@click.command()
@click.option(
    "--scenario", "-s",
    required=True,
    help="Free-text description of the economic scenario to stress-test.",
)
@click.option(
    "--ore-workspace",
    default=str(config.ORE_WORKSPACE),
    show_default=True,
    help="Path to the ORE workspace directory (must contain ore.xml, Input/, Output/).",
)
@click.option(
    "--scenario-id",
    default="agent_scenario",
    show_default=True,
    help="Identifier for the stress scenario in the ORE XML (no spaces).",
)
@click.option(
    "--output",
    "-o",
    default=None,
    help="Write the Markdown report to this file (prints to stdout if not set).",
)
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose output.")
def main(
    scenario: str,
    ore_workspace: str,
    scenario_id: str,
    output: str | None,
    verbose: bool,
) -> None:
    """Economic Scenario Stress Test Agent.

    Analyses a free-text economic scenario, maps it to historical market
    parallels, generates an ORE stress test, runs it, and prints a P&L report.
    """
    try:
        report = run(
            scenario_description=scenario,
            ore_workspace=Path(ore_workspace),
            scenario_id=scenario_id,
            verbose=verbose,
        )
    except EnvironmentError as exc:
        click.echo(f"\n{WARN} Configuration error: {exc}", err=True)
        sys.exit(1)
    except FileNotFoundError as exc:
        click.echo(f"\n{WARN} File not found: {exc}", err=True)
        sys.exit(1)
    except Exception as exc:  # noqa: BLE001
        click.echo(f"\n{WARN} Unexpected error: {exc}", err=True)
        if verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)

    if output:
        Path(output).write_text(report, encoding="utf-8")
        click.echo(f"Report written to: {output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
